### ISSUE TITLE
How to run it 

### ISSUE THREAD

**Issue by 9monsters** [pengqiuyuan/bbs#1]
I don't kown how to run it

**Comment by pengqiuyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/4953205/7646655/43f3e3be-faf9-11e4-8970-bf708e4f4c07.png)
![image](https://cloud.githubusercontent.com/assets/4953205/7646659/517c541c-faf9-11e4-9a86-586d4cb6149d.png)

**Comment by oldbig1982** [comment]
需要重新写数据库吗？我导入到myeclipse后不能运行,（我是新手，刚学了点struts2）

**Comment by pengqiuyuan** [comment]
导入 bbs.sql 之后， src/cn/iver/common/Config.java 下面有个 main 直接运行，项目就起来了

**Comment by wzj42685** [comment]
能不能看帖的？
